### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by hita03** [Tech-Matrix/Password-Manager#3]
**Is your feature request related to a problem? Please describe.**
Since this is a standalone program, we'd mostly want to copy the encrypted password onto our major application/what we use it for. Encrypted passwords/hashes are pretty long, and one takes time to confirm if the hashed password is correct.
**Describe the solution you'd like**
An additional copy-to-clipboard feature can be added, so it's easier for the user to to just click on a button to copy the password, without double-checking if it was copied correctly.
**Describe alternatives you've considered**
I couldn't come across a solution that was more appropriate. This feature is an easy one-time-fix to this problem, it can be implemented with tkinter.

I would like to be assigned to this issue.

**Comment by charvibannur** [comment]
Good Issue!! You've been assigned.
