### ISSUE TITLE
Random Password Generator

### ISSUE THREAD

**Issue by IshitaBharadwaj** [Tech-Matrix/Password-Manager#4]
**Is your feature request related to a problem? Please describe.**
Sometimes people find it hard to come up with difficult/complex passwords that would guarantee more security. So, there should be an option to generate a random and strong 8-12 character password for such users.

**Describe the solution you'd like**
There will be an option of 'Generate Random Password' apart from the text boxes for entering username and preferred password. The user can select this and get a new + random password for logging in when required. This is optional based on user's choice. This can be easily implemented using python.

**Describe alternatives you've considered**
There is no other appropriate way to generate a strong password so this seems feasible to accommodate in the project.

**Additional context**
No additional context.

I, Ishita, would like to be assigned to this issue.

**Comment by charvibannur** [comment]
You can get started, I've assigned it.
